# Generated by Django 5.2.7 on 2026-05-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='session_key',
        ),
    ]
